# Generated by Django 6.0 on 2025-12-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vehicle_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('Electric', 'Electric'), ('Petrol', 'Petrol'), ('Diesel', 'Diesel')], max_length=10)),
                ('maintenance_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driver_name', models.CharField(max_length=50)),
                ('paid_to_company', models.CharField(max_length=50)),
                ('bill_number', models.CharField(max_length=50)),
                ('bill_date', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
