# Generated by Django 6.0 on 2025-12-17 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_driver_remove_vehiclerecord_driver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclerecord',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.driver'),
            preserve_default=False,
        ),
    ]
