# Generated by Django 6.0 on 2025-12-17 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_vehiclerecord_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclerecord',
            old_name='remarks',
            new_name='reason_for_maintenance',
        ),
        migrations.AddField(
            model_name='vehiclerecord',
            name='distance_traveled',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehiclerecord',
            name='driver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.driver'),
        ),
    ]
